"""Abstract Metadata Repository — contract for lookup index backends."""

from abc import ABC, abstractmethod
from pathlib import Path
from .models import MetadataEntry, EntityType, SearchResult, SearchQuery


class AbstractMetadataRepository(ABC):
    @abstractmethod
    async def upsert(self, entry: MetadataEntry) -> None: ...
    @abstractmethod
    async def get_by_id(self, entity_id: str) -> MetadataEntry | None: ...
    @abstractmethod
    async def get_by_label(self, label: str, entity_type: EntityType | None = None) -> MetadataEntry | None: ...
    @abstractmethod
    async def search(self, query: SearchQuery) -> list[SearchResult]: ...
    @abstractmethod
    async def list_by_type(self, entity_type: EntityType) -> list[MetadataEntry]: ...
    @abstractmethod
    async def get_references(self, entity_id: str) -> list[MetadataEntry]: ...
    @abstractmethod
    async def build_from_wiki(self, wiki_dir: Path) -> int: ...
    @abstractmethod
    async def build_from_documents(self, documents: list[dict]) -> int: ...
    @abstractmethod
    async def clear(self) -> None: ...
    @abstractmethod
    async def stats(self) -> dict[str, int]: ...
